//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyLibrary {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TinyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TinyResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TinyLibrary.TinyResource", typeof(TinyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Program,If,Repeat,Identifier,Read,Write
        ///STMTSequence,If,Repeat,Identifier,Read,Write
        ///STMT_,Semicolon,ε
        ///Statement,If,Repeat,Identifier,Read,Write
        ///IfSTMT,If
        ///ElseSTMT,Else,ε
        ///RepeatSTMT,Repeat
        ///AssignSTMT,Identifier
        ///ReadSTMT,Read
        ///WriteSTMT,Write
        ///Exp,LeftBracket,Number,Identifier
        ///CmpExp_,LessThan,Equal,ε
        ///ComparisionOp,LessThan,Equal
        ///SimpleExp,LeftBracket,Number,Identifier
        ///Term_,Plus,Minus,ε
        ///AddOp,Plus,Minus
        ///Term,LeftBracket,Number,Identifier
        ///Factor_,Mul,Div,ε
        ///MulOp,Mul,Div
        ///Factor,LeftBracket,Nu [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TINYFirst {
            get {
                return ResourceManager.GetString("TINYFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program,θ
        ///STMTSequence,θ,Else,End,Until
        ///STMT_,θ,Else,End,Until
        ///Statement,Semicolon,θ,Else,End,Until
        ///IfSTMT,Semicolon,θ,Else,End,Until
        ///ElseSTMT,End
        ///RepeatSTMT,Semicolon,θ,Else,End,Until
        ///AssignSTMT,Semicolon,θ,Else,End,Until
        ///ReadSTMT,Semicolon,θ,Else,End,Until
        ///WriteSTMT,Semicolon,θ,Else,End,Until
        ///Exp,Then,Semicolon,θ,RightBracket,Else,End,Until
        ///CmpExp_,Then,Semicolon,θ,RightBracket,Else,End,Until
        ///ComparisionOp,LeftBracket,Number,Identifier
        ///SimpleExp,LessThan,Equal,Then,Semicolon,θ,RightBracket,El [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TINYFollow {
            get {
                return ResourceManager.GetString("TINYFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program,STMTSequence
        ///STMTSequence,Statement,STMT_
        ///STMT_,Semicolon,Statement,STMT_
        ///STMT_,ε
        ///Statement,IfSTMT
        ///Statement,RepeatSTMT
        ///Statement,AssignSTMT
        ///Statement,ReadSTMT
        ///Statement,WriteSTMT
        ///IfSTMT,If,Exp,Then,STMTSequence,ElseSTMT,End
        ///ElseSTMT,Else,STMTSequence
        ///ElseSTMT,ε
        ///RepeatSTMT,Repeat,STMTSequence,Until,Exp
        ///AssignSTMT,Identifier,Assign,Exp
        ///ReadSTMT,Read,Identifier
        ///WriteSTMT,Write,Exp
        ///Exp,SimpleExp,CmpExp_
        ///CmpExp_,ComparisionOp,SimpleExp
        ///CmpExp_,ε
        ///ComparisionOp,LessThan
        ///ComparisionOp,E [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TINYRules {
            get {
                return ResourceManager.GetString("TINYRules", resourceCulture);
            }
        }
    }
}
